repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args: [--profile, black]

-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    -   id: black
        args: [--line-length=120]

-   repo: https://github.com/ikamensh/flynt/
    rev: '0.63'
    hooks:
    -   id: flynt

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: ^airflow/dags/(tables|factory|queries)/
    -   id: end-of-file-fixer
        exclude: ^airflow/dags/(tables|factory|queries)/
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: check-yaml
        exclude: ^(|airflow/)cloudformation/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
    -   id: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]
